# Generated by Django 4.2.13 on 2024-06-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_chatmessage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
