# Generated by Django 4.2.13 on 2024-08-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_activitylog_delete_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
