# Generated by Django 4.2.13 on 2024-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_remove_activitylog_details_activitylog_edited_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="task_title",
            field=models.CharField(max_length=255),
        ),
    ]
