# Generated by Django 4.2.13 on 2024-08-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_project_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="project",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="tasks.project",
            ),
            preserve_default=False,
        ),
    ]
