# Generated by Django 4.2.9 on 2024-08-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_subtask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubTask",
        ),
    ]
