# Generated by Django 4.2.9 on 2024-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
